import 'package:flutter_test/flutter_test.dart';
import 'package:googleapis/calendar/v3.dart' as gcal;

import 'package:solo_todo/src/features/calendar/event_import_filter.dart';

void main() {
  gcal.Event event({
    String? id = 'ev-1',
    String? status,
    bool? organizerSelf,
    String? myResponse,
    String? eventType,
    Map<String, String>? private,
    bool timed = true,
  }) {
    final e = gcal.Event(
      id: id,
      summary: '일정',
      status: status,
      eventType: eventType,
      start: timed
          ? gcal.EventDateTime(dateTime: DateTime.utc(2026, 8, 20, 10))
          : gcal.EventDateTime(date: DateTime(2026, 8, 20)),
      end: timed
          ? gcal.EventDateTime(dateTime: DateTime.utc(2026, 8, 20, 11))
          : gcal.EventDateTime(date: DateTime(2026, 8, 21)),
    );
    if (organizerSelf != null) {
      e.organizer = gcal.EventOrganizer(self: organizerSelf);
    }
    if (myResponse != null) {
      e.attendees = [
        gcal.EventAttendee(self: true, responseStatus: myResponse),
        gcal.EventAttendee(email: 'other@example.com'),
      ];
    }
    if (private != null) {
      e.extendedProperties = gcal.EventExtendedProperties(private: private);
    }
    return e;
  }

  ImportVerdict judge(
    gcal.Event e, {
    bool importInvited = false,
    Set<String> knownTodoIds = const {},
  }) =>
      judgeImport(e, importInvited: importInvited, knownTodoIds: knownTodoIds);

  group('기본 — 내가 만든 일정만 들어온다', () {
    test('주최자가 나면 통과', () {
      expect(judge(event(organizerSelf: true)), ImportVerdict.accept);
    });

    test('주최자 정보가 없으면 통과 — 개인 캘린더의 단독 일정', () {
      expect(judge(event()), ImportVerdict.accept);
    });

    test('남이 만든 일정은 기본적으로 제외', () {
      expect(judge(event(organizerSelf: false)), ImportVerdict.skipInvited);
    });

    test('설정을 켜면 초대받은 일정도 통과', () {
      expect(
        judge(event(organizerSelf: false), importInvited: true),
        ImportVerdict.accept,
      );
    });
  });

  group('항상 제외', () {
    test('취소된 이벤트 — 유입이 아니라 삭제 신호다', () {
      expect(judge(event(status: 'cancelled')), ImportVerdict.cancelled);
    });

    test('내가 거절한 일정은 설정과 무관하게 제외', () {
      expect(
        judge(
          event(organizerSelf: false, myResponse: 'declined'),
          importInvited: true,
        ),
        ImportVerdict.skipDeclined,
      );
    });

    test('생일 이벤트', () {
      expect(
        judge(event(eventType: 'birthday')),
        ImportVerdict.skipAutoGenerated,
      );
    });

    test('Gmail 자동 생성 이벤트', () {
      expect(
        judge(event(eventType: 'fromGmail')),
        ImportVerdict.skipAutoGenerated,
      );
    });

    test('id 가 없으면 링크할 수 없어 제외', () {
      expect(judge(event(id: null)), ImportVerdict.skipUnusable);
    });
  });

  group('앱이 만든 이벤트는 유입 대상이 아니다', () {
    test('아는 할 일 서명이 있으면 제외 — 이미 우리 것이다', () {
      expect(
        judge(
          event(private: {'haruTodoId': 'todo-1'}),
          knownTodoIds: {'todo-1'},
        ),
        ImportVerdict.skipOwnEvent,
      );
    });

    test('서명은 있지만 로컬에 없는 할 일이면 통과 — 링크가 끊긴 이벤트 복구', () {
      expect(
        judge(
          event(private: {'haruTodoId': 'todo-사라짐'}),
          knownTodoIds: {'todo-1'},
        ),
        ImportVerdict.accept,
      );
    });
  });

  group('수락 상태', () {
    test('수락한 초대는 설정을 켜면 통과', () {
      expect(
        judge(
          event(organizerSelf: false, myResponse: 'accepted'),
          importInvited: true,
        ),
        ImportVerdict.accept,
      );
    });

    test('미응답 초대도 설정을 켜면 통과', () {
      expect(
        judge(
          event(organizerSelf: false, myResponse: 'needsAction'),
          importInvited: true,
        ),
        ImportVerdict.accept,
      );
    });
  });

  test('accept 만 유입이다', () {
    expect(ImportVerdict.accept.isAccepted, isTrue);
    for (final v in ImportVerdict.values.where(
      (v) => v != ImportVerdict.accept,
    )) {
      expect(v.isAccepted, isFalse, reason: '$v');
    }
  });
}
