import 'package:googleapis/calendar/v3.dart' as gcal;

import 'event_to_todo.dart';

/// 수신한 이벤트를 할 일로 들일지의 판정 결과.
///
/// 거절 사유를 값으로 남기는 이유 — 호출자가 "취소됨"(삭제 규칙으로 넘김)과 그냥
/// "안 들임"(무시)을 구분해야 하고, 설정 화면에서 "왜 안 들어왔는지" 를 설명할 수
/// 있어야 하기 때문이다. bool 하나면 그 정보가 사라진다.
enum ImportVerdict {
  /// 할 일로 들인다.
  accept,

  /// 취소된 이벤트 — 유입이 아니라 **삭제 신호**다. 호출자가 삭제 규칙으로 넘긴다.
  cancelled,

  /// 남이 만든 일정인데 "초대받은 일정 가져오기" 가 꺼져 있다.
  skipInvited,

  /// 내가 거절한 일정 — 설정과 무관하게 제외.
  skipDeclined,

  /// 생일·공휴일·Gmail 자동 생성 등 시스템이 만든 이벤트.
  skipAutoGenerated,

  /// 앱이 만든 이벤트 — 이미 우리 할 일이다.
  skipOwnEvent,

  /// id 가 없어 링크할 수 없는 이벤트.
  skipUnusable;

  bool get isAccepted => this == ImportVerdict.accept;
}

/// 시스템이 자동 생성해 할 일로서 의미가 없는 이벤트 종류.
const _autoGeneratedTypes = {'birthday', 'fromGmail', 'workingLocation'};

/// 이 이벤트를 할 일로 들일지 판정한다.
///
/// 읽기 캘린더를 켜는 순간 남이 초대한 회의까지 할 일 목록에 쏟아지면 앱이 망가진다.
/// 그래서 **기본은 "내가 만든 일정만"** 이고, 초대받은 일정은 설정으로 명시적으로
/// 켜야 들어온다.
///
/// - [importInvited] — 설정의 "초대받은 일정도 가져오기"
/// - [knownTodoIds] — 로컬에 존재하는 할 일 id 집합. 앱이 만든 이벤트를 되들이지
///   않기 위해 쓴다. 서명은 있는데 로컬에 없는 할 일이면 **통과시킨다** — 링크가
///   끊긴 이벤트를 되살리는 복구 경로다.
ImportVerdict judgeImport(
  gcal.Event event, {
  required bool importInvited,
  required Set<String> knownTodoIds,
}) {
  if (event.status == 'cancelled') return ImportVerdict.cancelled;
  if ((event.id ?? '').isEmpty) return ImportVerdict.skipUnusable;

  final type = event.eventType;
  if (type != null && _autoGeneratedTypes.contains(type)) {
    return ImportVerdict.skipAutoGenerated;
  }

  final signedTodoId = readHaruSignature(event).todoId;
  if (signedTodoId != null && knownTodoIds.contains(signedTodoId)) {
    return ImportVerdict.skipOwnEvent;
  }

  // 내 응답 상태 — attendees 중 self 인 항목.
  final me = event.attendees?.where((a) => a.self == true).firstOrNull;
  if (me?.responseStatus == 'declined') return ImportVerdict.skipDeclined;

  // organizer.self 가 명시적으로 false 일 때만 "남의 일정" 으로 본다.
  // 개인 캘린더의 단독 일정은 organizer 정보가 아예 없는 경우가 흔한데, 그걸
  // 남의 것으로 취급하면 정작 내 일정이 하나도 안 들어온다.
  final notMine = event.organizer?.self == false;
  if (notMine && !importInvited) return ImportVerdict.skipInvited;

  return ImportVerdict.accept;
}
